---
- name: Download SonarQube
  unarchive:
    src: "{{ sonarqube_download_url }}"
    dest: "{{ sonarqube_install_tmp_base_dir }}"
    remote_src: yes
    creates: "{{ sonarqube_service_file_path }}"

- name: Install SonarQube
  copy:
    src: "{{ sonarqube_install_tmp_dir }}/"
    dest: "{{ sonarqube_install_dir }}/"
    remote_src: yes

- name: Change file permission of SonarQube installation directory
  file:
    dest: "{{ sonarqube_install_dir }}"
    owner: "{{ sonarqube_user }}"
    group: "{{ sonarqube_group }}"
    recurse: yes
